apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ds
  labels:
    app: nginx-ds
spec:
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: nginx-ds
        image: nginx:1.7.9
        ports:
        - containerPort: 80