apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-redis
  labels:
    app: nginx-redis
spec:
  minReadySeconds: 5
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: nginx-redis
  template:
    metadata:
      labels:
        app: nginx-redis
    spec:
      containers:
      - name: nginx-redis
        image: nginx:1.7.9
        imagePullPolicy: Always
        ports:
        - containerPort: 80